services:
  postgres:
    image: postgres:16.3
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    secrets:
      - postgres-password
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    shm_size: 256m
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d/
  pgAdmin:
    image: dpage/pgadmin4:8.10
    ports:
      - "127.0.0.1:5050:80"
    depends_on:
      - postgres
    secrets:
      - pgadmin-password
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@company.tdl
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin-password
    volumes:
      - pgAdmin-data:/var/lib/pgadmin
  grafana:
    image: grafana/grafana:11.1.2
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: marcusolsson-treemap-panel
      GF_ANALYTICS_ENABLED: false
      GF_ANALYTICS_REPORTING_ENABLED: false
      GF_ANALYTICS_CHECK_FOR_UPDATES: false
      GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES: false
      GF_ANALYTICS_FEEDBACK_LINKS_ENABLED: false

volumes:
  postgres-data:
  pgAdmin-data:
  grafana-data:

secrets:
  postgres-password:
    file: ./secrets/postgres-pass.txt
  pgadmin-password:
    file: ./secrets/pgadmin-pass.txt
