apiVersion: 1

datasources:
  - name: sqlite-datasource
    uid: sqlite-ds
    type: frser-sqlite-datasource
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      path: /data/sqlite3.db
