apiVersion: 1

datasources:
  - name: postgres-datasource
    uid: pgds #THIS IS IMPORTANT ON THE DASHBOARD MUST BE THE SAME
    orgId: 1
    type: postgres
    access: proxy
    url: postgres:5432
    database: admin
    user: admin
    basicAuth: false
    secureJsonData:
      password: "admin"
    jsonData:
      sslmode: "disable"
      tlsAuth: false
      tlsAuthWithCACert: false
      connMaxLifetime: 14400
      postgresVersion: 903
      timescaledb: false
    isDefault: true
