{
 "title": "Main Overview",
 "time": { "from": "now/y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "commodity",
    "label": "Default Commodity",
    "query": "select currency from hledger.main_commodities"
   },
   { "name": "age", "label": "Current Age", "query": "40,41,42,43,44,45,46,47,48,49" },
   { "name": "credit_limit", "label": "Credit Limit", "query": "9000" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Net Worth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select\n\ta.date,\n\ta.net_worth as \"Net Worth\"\nfrom hledger.net_worth a\nwhere \n\ta.currency = '${commodity}' and\n\ta.date <= '${__to:date:yyyy-MM-DD}'\n"
    }
   ]
  },
  {
   "title": "Short Runaway",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\ta.date,\n\ta.balance / b.daily_expense as short_runaway\nfrom (\n\tselect\n\t\ta.date,\n\t\tsum(a.balance) as balance\n\tfrom hledger.balance_to_date_converted a \n\tjoin hledger.assets_classification b on\n\t\ta.account = b.account and\n\t\tb.classification in (\n\t\t\t'Cash',  \n\t\t\t'Savings'\n\t\t) \n\twhere\n\t\ta.currency = '${commodity}'\n\tgroup by\n\t\ta.date\t\n) a\njoin hledger.average_daily_expenses b on\n\ta.date = b.date\nwhere\n\tb.currency = '${commodity}' and\n\tb.daily_expense is not null and\n\ta.date <= '${__to:date:yyyy-MM-DD}'\n\n"
    }
   ]
  },
  {
   "title": "Long Runaway",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\ta.date,\n\ta.balance / b.daily_expense as long_runaway\nfrom hledger.balance_to_date_converted a\njoin hledger.average_daily_expenses b on\n\ta.date = b.date and\n\ta.currency = b.currency\nwhere\n\ta.account = 'Assets' and\n\ta.currency = '${commodity}' and\n\tb.daily_expense is not null and\n\ta.date <= '${__to:date:yyyy-MM-DD}'\n"
    }
   ]
  },
  {
   "title": "FIRE Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\ta.date,\n\ta.net_worth / (b.daily_expense * 365 * 25) as fire_percentage\nfrom hledger.net_worth a\njoin hledger.average_daily_expenses b on\n\ta.date = b.date and\n\ta.currency = b.currency\nwhere\n\ta.currency = '${commodity}' and\n\ta.date <= '${__to:date:yyyy-MM-DD}'\n"
    }
   ]
  },
  {
   "title": "Expected Wealth",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\ta.date,\n\tb.net_worth,\n\t0 as baseline,\n\t-1 * a.daily_income * 365 * ${age:raw} / 10 / 2 as under_wealth,\n\t-1 * a.daily_income * 365 * ${age:raw} / 10 as expected_wealth,\n\t-1 * a.daily_income * 365 * ${age:raw} / 10 * 2 as over_wealth\nfrom hledger.average_daily_income a\njoin hledger.net_worth b on\n\ta.date = b.date and\n\ta.currency = b.currency\nwhere\n\ta.currency = '${commodity}' and\n\ta.date <= '${__to:date:yyyy-MM-DD}'\n\n"
    }
   ]
  },
  {
   "title": "Assets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  a.date,\n\tb.classification,\n\tsum(balance) as amount\nfrom hledger.balance_to_date_converted a\njoin hledger.assets_classification b on\n\ta.account = b.account\nwhere\n\tcurrency = '${commodity}' and\n\ta.date <= '${__to:date:yyyy-MM-DD}'\ngroup by\n\ta.date,\n\tb.classification\norder by\n\ta.date"
    }
   ]
  },
  {
   "title": "Daily Averages (Last Year)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\r\n\ta.date,\r\n\ta.daily_expense as \"Expenses\",\r\n\t-1 * b.daily_income as \"Income\",\r\n\t1 - ((-1 * a.daily_expense) / b.daily_income) as \"Ratio\"\r\nfrom hledger.average_daily_expenses a\r\njoin hledger.average_daily_income b on\r\n\ta.date = b.date and\r\n\ta.currency = b.currency\r\nwhere\r\n\ta.daily_expense is not null and\r\n\tb.daily_income is not null and\r\n\ta.currency = '${commodity}'  and\r\n\ta.date <= '${__to:date:yyyy-MM-DD}'\r\n"
    }
   ]
  },
  {
   "title": "Credit Utilization Ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\r\n\ta.date,\r\n\t-1 * sum(balance) / ${credit_limit} as \"Ratio\"\r\nfrom hledger.balance_to_date_converted a\r\nwhere\r\n\ta.currency = '${commodity}' and\r\n\ta.account = 'Liabilities' and\r\n\ta.date <= '${__to:date:yyyy-MM-DD}'\r\ngroup by\r\n\ta.date\r\norder by\r\n\ta.date"
    }
   ]
  },
  { "title": "Assets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Assets Distribution",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select\r\n  a.date,\r\n\tb.classification,\r\n\tsum(balance) as amount\r\nfrom hledger.balance_to_date_converted a\r\njoin hledger.assets_classification b on\r\n\ta.account = b.account\r\nwhere\r\n\tcurrency = '${commodity}' and\r\n\ta.date <= '${__to:date:YYYY-MM-DD}'\r\ngroup by\r\n\ta.date,\r\n\tb.classification\r\norder by \r\n\ta.date desc"
    }
   ]
  },
  {
   "title": "Weighted Allocation",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    { "panelId": 16 }
   ]
  },
  {
   "title": "Cost Allocation",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    { "panelId": 16 }
   ]
  },
  {
   "title": "Ratios",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Debt-to-Income Ratio *",
     "type": "timeseries",
     "description": "Debt-to-income (DTI) ratio is the percentage of your monthly gross income that goes to paying your monthly debt payments and is used by lenders to determine your borrowing risk.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "select\r\n\ta.date,\r\n\t-1 * sum(case when a.account = 'Liabilities' then balance else 0 end) as \"Liabilities\",\r\n\t-1 * sum(case when a.account = 'Income' then balance else 0 end) as \"Income\",\r\n\t(\r\n\t\tsum(case when a.account = 'Liabilities' then balance else 0 end) /\r\n\t\tsum(case when a.account = 'Income' then balance else 0 end)\r\n\t) as \"Ratio\"\r\nfrom hledger.balance_to_date_converted a\r\nwhere\r\n\ta.currency = '${commodity}' and\r\n\ta.account in (\r\n\t\t'Liabilities',\r\n\t\t'Income'\r\n\t) and\r\n\t$__timeFilter(a.date)\r\ngroup by\r\n\ta.date\r\norder by\r\n\ta.date"
      }
     ]
    },
    {
     "title": "Debt-to-Net Worht Ratio",
     "type": "timeseries",
     "description": "The debt-to-net worth formula is a good one to be familiar with, as it can shed light on how financially healthy you are -- for you or for anyone assessing your financial condition.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "select\r\n\ta.date,\r\n\t-1 * sum(case when a.account = 'Liabilities' then balance else 0 end) as \"Liabilities\",\r\n\tsum(balance) as \"Net Worth\",\r\n\t(\r\n\t\t(-1 * sum(case when a.account = 'Liabilities' then balance else 0 end)) /\r\n\t\tsum(balance)\r\n\t) as \"Ratio\"\r\nfrom hledger.balance_to_date_converted a\r\nwhere\r\n\ta.currency = '${commodity}' and\r\n\ta.account in (\r\n\t\t'Liabilities',\r\n\t\t'Assets'\r\n\t) and\r\n\t$__timeFilter(a.date)\r\ngroup by\r\n\ta.date\r\norder by\r\n\ta.date"
      }
     ]
    },
    {
     "title": "Debt-to-Assets Ratio",
     "type": "timeseries",
     "description": "The Debt to Asset Ratio, also known as the debt ratio, is a leverage ratio that indicates the percentage of assets financed with debt. The higher the ratio, the greater the leverage and financial risk degree.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "select\r\n\ta.date,\r\n\t-1 * sum(case when a.account = 'Liabilities' then balance else 0 end) as \"Liabilities\",\r\n\tsum(case when a.account = 'Assets' then balance else 0 end) as \"Assets\",\r\n\t(\r\n\t\t(-1 * sum(case when a.account = 'Liabilities' then balance else 0 end)) /\r\n\t\tsum(case when a.account = 'Assets' then balance else 0 end)\r\n\t) as \"Ratio\"\r\nfrom hledger.balance_to_date_converted a\r\nwhere\r\n\ta.currency = '${commodity}' and\r\n\ta.account in (\r\n\t\t'Liabilities',\r\n\t\t'Assets'\r\n\t) and\r\n\t$__timeFilter(a.date)\r\ngroup by\r\n\ta.date\r\n"
      }
     ]
    },
    {
     "title": "(Moving Average) Cash Flow Ratio",
     "type": "timeseries",
     "description": "The cash flow ratio helps you understand what percentage of your income is dedicated to your expenses. Think about the cash flow ratio as how much cash flows in vs flowing out.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "select\r\n\ta.date,\r\n\ta.daily_expense as \"Expenses\",\r\n\t-1 * b.daily_income as \"Income\",\r\n\t((-1 * a.daily_expense) / b.daily_income) as \"Ratio\"\r\nfrom hledger.average_daily_expenses a\r\njoin hledger.average_daily_income b on\r\n\ta.date = b.date and\r\n\ta.currency = b.currency\r\nwhere\r\n\ta.daily_expense is not null and\r\n\tb.daily_income is not null and\r\n\ta.currency = '${commodity}' and\r\n\ta.date between '${__from:date:YYYY-MM-DD}' and '${__to:date:YYYY-MM-DD}'\r\n"
      }
     ]
    },
    {
     "title": "(Moving Average) Savings Ratio",
     "type": "timeseries",
     "description": "The savings ratio is a measure of the proportion of an individual's income that is saved rather than spent on consumption. It is expressed as a percentage and indicates the financial health and stability of an individual.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "select\r\n\ta.date,\r\n\tsum(a.daily_savings) as \"Savings\",\r\n\tsum(-1 * b.daily_income) as \"Income\",\r\n\t-1 * sum(a.daily_savings / b.daily_income) as \"Ratio\"\r\nfrom hledger.average_daily_savings a\r\njoin hledger.average_daily_income b on\r\n\ta.date = b.date and\r\n\ta.currency = b.currency\r\nwhere\r\n\ta.daily_savings is not null and\r\n\tb.daily_income is not null and\r\n\ta.currency = '${commodity}' and\r\n\ta.date between '${__from:date:YYYY-MM-DD}' and '${__to:date:YYYY-MM-DD}'\r\ngroup by\r\n\ta.date\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Retirement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Retirement Grow",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "select\r\n\ta.date,\r\n\tsum(balance) as \"Retirement\"\r\nfrom hledger.balance_to_date_converted a\r\njoin hledger.assets_classification b on\r\n\ta.account = b.account\r\nwhere\r\n\ta.currency = '${commodity}' and\r\n\tb.classification = 'Retirement' \r\ngroup by\r\n\ta.date\r\norder by\r\n\tdate desc\r\n"
      }
     ]
    },
    {
     "title": "Yearly Savings",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "select\r\n\ta.date,\r\n\t-1 * sum(case when a.account = 'Income' then a.balance else 0 end) over (order by a.date) as \"Income\",\r\n\tsum(case when a.account != 'Income' then a.balance else 0 end) over (order by a.date) as \"Retirement\",\r\n\tsum(case when a.account != 'Income' then a.balance else 0 end) over (order by a.date) / \r\n\t(-1 * sum(case when a.account = 'Income' then a.balance else 0 end) over (order by a.date)) as \"Ratio\"\r\nfrom hledger.daily_delta_converted a\r\nleft join hledger.assets_classification b on\r\n\ta.account = b.account\r\nwhere\r\n\t$__timeFilter(a.date) and\r\n\t(\r\n\t\ta.account ='Income' or\r\n\t\tb.classification = 'Retirement'\r\n\t) and\r\n\ta.currency = '${commodity}'\r\norder by\r\n\ta.date"
      }
     ]
    }
   ]
  }
 ]
}